# Generated by Django 3.0.6 on 2020-06-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem", unique_together={("order", "product")},
        ),
    ]
