# Generated by Django 3.0.6 on 2020-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_auto_20200603_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="amount", field=models.PositiveIntegerField(),
        ),
    ]
